#!/bin/bash

set -euo pipefail

wget https://github.com/cytoscape/cytoscape/releases/download/3.7.2/cytoscape-3.7.2.tar.gz
tar xf cytoscape-3.7.2.tar.gz
rm cytoscape-3.7.2.tar.gz
mkdir /home/jovyan/Desktop
mv cytoscape-unix-3.7.2 /home/jovyan/Desktop/
chown -R jovyan:jovyan /home/jovyan/Desktop/cytoscape-unix-3.7.2
