#!/bin/bash

set -euo pipefail

cp -r binder/Desktop ${HOME}/Desktop

wget https://github.com/cytoscape/cytoscape/releases/download/3.7.2/cytoscape-3.7.2.tar.gz
tar xf cytoscape-3.7.2.tar.gz
rm cytoscape-3.7.2.tar.gz
